"""data access functions for employee-related operations in MongoDB."""
from datetime import datetime, timezone
from typing import Optional

from bson import ObjectId
from bson.errors import InvalidId

from app.database.mongodb import employees_collection

ALLOWED_SORT_FIELDS = {"salary","joining_date", "first_name", "second_name", "department", "designation"}

def_next_employee_id() -> str:
    """Generate the next sequence employee_id  in the format EMP-0001, EMP-0002, etc."""
    """uses the count of existing employees to generate the next employee_id, ensuring uniqueness and sequential order."""
    count = employees_collection.count_documents({})
    return f"EMP-{count + 1:04d}"

def serialize_employee(employee_doc: dict) -> dict:
    """convert a mongodb document into JSON-serializable dict"""
    joining_date = employee_doc["joining_date"]
    if isinstance(joining_date, datetime):
        joining_date = joining_date.date()
    return {
        "id": str(employee_doc["_id"]),
        "employee_id": employee_doc["employee_id"],
        "first_name": employee_doc["first_name"],
        "second_name": employee_doc["second_name"],
        "email": employee_doc["email"],
        "phone_number": employee_doc["phone_number"],
        "department": employee_doc["department"],
        "designation": employee_doc["designation"],
        "salary": employee_doc["salary"],
        "joining_date": employee_doc["joining_date"],
        "is_active": employee_doc["is_active"],
        "profile_picture": employee_doc.get("profile_picture"),
        "created_at": employee_doc["created_at"],
        "updated_at": employee_doc["updated_at"]
    }

def create_employee(data:dict)->dict:
    """insert a new employee document into the employees collection with a unique employee_id generated by _next_employee_id(). 
    """
    now = datetime.now(timezone.utc)
    document = {
        "employee_id": _next_employee_id(),
        "first_name": data["first_name"],
        "second_name": data["second_name"],
        "email": data["email"],
        "phone_number": data["phone_number"],
        "department": data["department"],
        "designation": data["designation"],
        "salary": data["salary"],
        "joining_date": datetime.combine(data["joining_date"], datetime.min.time()),
        "is_active": True,
        "profile_picture": None,
        "created_at" : now,
        "updated_at": now,
    }
    result = employees_collection.insert_one(document)
    document["_id"] = result.inserted_id
    return document

#Retry a few times in the unlikely event of an employee_id collision due to concurrent inserts. This is a rare case, but we handle it gracefully.
    last_error = None
    for_in range(5):
        document["employee_id"] = _next_employee_id()
        try:
            result = employees_collection.insert_one(document)
            return document
        except Exception as exc: #noqa: BLE001 -re-raise after retries
            last_error = exc
            continue
    raise last_error

def get_employee_by_id(employee_id:str)->Optional[dict]:
    """Fetch a raw employee document from the employees collection by its MongoDB ObjectId. Returns None if not found or if the provided ID is invalid."""
    try:
        object_id = ObjectId(employee_id)
    except (InvalidId, TypeError):
        return None
    return employees_collection.find_one({"_id": object_id})

def get_employee_by_email(email:str)->Optional[dict]:
    """Fetch a raw employee document from the employees collection by its email. Returns None if not found."""
    return employees_collection.find_one({"email": email.lower()})

def update_employee(employee_id:str, update_data:dict)->Optional[dict]:
    """Update an existing employee document in the employees collection by its MongoDB ObjectId. Returns the updated document or None if not found."""
    try:
        object_id = ObjectId(employee_id)
    except (InvalidId, TypeError):
        return None
    if "joining_date"in update_data and isinstance(update_data["joining_date"], datetime):
        update_data["joining_date"] = datetime.combine(update_data["joining_date"], datetime.min.time())
    if "email" in update_data and update_data["email"] is not None:
        update_data["email"] = update_data["email"].lower()
    update_data["updated_at"] = datetime.now(timezone.utc)

    employees_collection.update_one({"_id": object_id}, {"$set": update_data})
    return employees_collection.find_one({"_id": object_id})


def set_profile_picture(employee_id:str,filename:str)->Optional[dict]:
    """Update the profile_picture field of an employee document in the employees collection by its MongoDB ObjectId. Returns the updated document or None if not found."""
    try:
        object_id = ObjectId(employee_id)
    except (InvalidId, TypeError):
        return None
    update_data = {
        "profile_picture": filename,
        "updated_at": datetime.now(timezone.utc)
    }
    employees_collection.update_one({"_id": object_id},
    {"$set": update_data})
    return employees_collection.find_one({"_id": object_id})

def soft_delete_employee(employee_object_id:str)->Optional[dict]:
    """Soft delete an employee document by setting its is_active field to False. Returns the updated document or None if not found."""
    try:
        object_id = ObjectId(employee_object_id)
    except (InvalidId, TypeError):
        return None
    
    employees_collection.update_one({"_id": object_id}, 
    {"$set": update_data})
    return employees_collection.find_one({"_id": object_id})

def list_employees(
    name: Optional[str] = None,
    department: Optional[str] = None,
    designation: Optional[str] = None,
    min_salary: Optional[float] = None,
    max_salary: Optional[float] = None,
    is_active: Optional[bool] = None,
    joining_year: Optional[int] = None,
    sort_by: Optional[str] = None,
    sort_order: str = "asc",
    page: int = 1,  
    limit: int = 10,
    offset: int = 0
) -> dict:
   """Query employees  with search, filter,sorting and pagination options. Returns a dictionary containing the total count, current page, limit, and a list of serialized employee documents."""
   query = {}
   if name:
       query["$or"] = [
           {"first_name": {"$regex": name, "$options": "i"}},
           {"second_name": {"$regex": name, "$options": "i"}}
       ]
   if department:
       query["department"] = {"$regex":f"^{department}$","$options":"i"}
   if designation:
       query["designation"] = {"$regex":f"^{designation}$","$options":"i"}

   if is active is not None:
       query["is_active"] = is_active

    salary_filter = {}

       if min_salary is not None:
           salary_filter["$gte"] = min_salary
       if max_salary is not None:
           salary_filter["$lte"] = max_salary
       query["salary"] = salary_filter
   if is_active is not None:
       query["is_active"] = is_active
   if joining_year is not None:
       start_date = datetime(joining_year, 1, 1)
       end_date = datetime(joining_year + 1, 1, 1)
       query["joining_date"] = {"$gte": start_date, "$lt": end_date}

   total_count = employees_collection.count_documents(query)
   cursor = employees_collection.find(query)

   if sort_by:
     field = sort_by if sort_by in ALLOWED_SORT_FIELDS else "first_name"
     direction = 1 if sort_order.lower() == "asc" else -1
     cursor = cursor.sort(field, direction)
    else:
        cursor = cursor.sort("created_at", -1)

    skip = (page - 1) * limit
    cursor = cursor.skip(skip).limit(limit)
   
   return total_count, list(cursor)






